language: python
dist: xenial
sudo: true

# Limit git depth to speed up build
git:
  depth: 5

matrix:
  include:
  # - python: 3.5
  #   env:
  #   - TOXENV=py35
  # - python: 3.6
  #   env:
  #   - TOXENV=py36
  # - python: 3.7
  #   env:
  #   - TOXENV=py37
  # - python: 3.8-dev
  #   env:
  #   - TOXENV=py38
  - python: 3.7
    env: TOXENV=lint
  - python: 3.7
    env: TOXENV=documents
  allow_failures:
  - python: 3.8-dev

addons:
  apt:
    packages:
    - aspell
    - aspell-en

install:
- pip install tox
# - pip install codecov

script:
- tox

# after_success:
# - codecov

deploy:
  - provider: pypi
    user: facelessuser
    server: https://upload.pypi.org/legacy/
    password:
      secure: RGPJ/fcKBnS5CVeb7KsZXfIRoxOFbrJ+PuSap7mBD5T+ECtNaA4gwoQw1cLmN1wLCjvMrXcUeMJSlOiHD8FwMxmKSx7xKBjPBFJ9VuQcSTR+vWPdT/amYZn/5zJW5iChX9ChlUXAk4iB5Tr1cqNVUPRZova9t+DrmtsdIDd10UbvUjB2FWLMTtMnAkuk2v+1AMdj0xTPPRauM6uFnDLHdQcE93Ca92iKjZva4/tVCm+MomnYSUVqrcpN3P9Q+O3ZUT7omejqgoMO/WgoOinaqCi8xIR6DG+tUnPWPBPAkwXrKJJbTY4AJLAZeb/RhhcCS1qPjNKP3LYqlOBFGa4N4qMnEd6oWR97IrxdiGWEVBrPqfcKLSJzRwPWrC3fap1/yzsBx+CrI6tstkavmkB4chAVhn0c2fqyKHZ9/ouzqUpP9PvPfaJd9SJCxNDiepg+Ey8IZufVcJRqlbHvXrzxXstoLdvqSyMkze1sZPH+qCVK7sCzgFOhVj7K6Jh6/zxWiQ9lS+WPky0QE4dI7qdEoLKNvoJAhBRxGZzDj9+BHk7Wc/6oomhBt4X/U1r+FMx1urpF5YIcsCU1Ma189yvXybHJtW7LlqoqgVCgf19LbKOqkb5QKKdDMAmP/XBpuPR+oU0Jjngjcj5+nG1AD4+YwSYfhDz8qDjfvxv0psysyKk=
    skip_upload_docs: true
    on:
      tags: true
      repo: facelessuser/pyluxa4
      condition: "$TOXENV = documents"
  # - provider: pages
  #   github_token: $GITHUB_TOKEN
  #   name: $GITHUB_USER
  #   email: $GITHUB_EMAIL
  #   skip_cleanup: true
  #   local_dir: site
  #   on:
  #     tags: true
  #     repo: facelessuser/pyluxa4
  #     condition: "$TOXENV = documents"
